// react-19-rc/src/components/Statistics.jsx
import PropTypes from "prop-types"
import { useEffect, useState } from "react"

export default function Statistics({ title, posts, comments, users }) {
  const [currentDate, setCurrentDate] = useState(new Date().toISOString())

  useEffect(() => {
    setCurrentDate(new Date().toISOString())
  })

  return (
    <div>
      <h3 className="mb-2">{title}</h3>
      <h4 className="mb-2">Updated at: {currentDate}</h4>
      <ul className="stats-list">
        <li>
          Posts: <span>{posts}</span>
        </li>
        <li>
          Comments: <span>{comments}</span>
        </li>
        <li>
          Users: <span>{users}</span>
        </li>
      </ul>
    </div>
  )
}

Statistics.propTypes = {
  title: PropTypes.string,
  posts: PropTypes.number,
  comments: PropTypes.number,
  users: PropTypes.number,
}

// vue-3/src/components/Statistics.vue
<template>
  <div>
    <h3 class="mb-2">{{ title }}</h3>
    <h4 class="mb-2">Updated at: {{ currentDate }}</h4>
    <ul class="stats-list">
      <li>
        Posts: <span>{{ posts }}</span>
      </li>
      <li>
        Comments: <span>{{ comments }}</span>
      </li>
      <li>
        Users: <span>{{ users }}</span>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'StatisticsCard',
  props: {
    title: {
      type: String,
      required: true
    },
    posts: {
      type: Number,
      required: true
    },
    comments: {
      type: Number,
      required: true
    },
    users: {
      type: Number,
      required: true
    }
  },
  data() {
    return {
      currentDate: new Date().toISOString()
    };
  },
  watch: {
    title() {
      this.updateCurrentDate();
    },
    posts() {
      this.updateCurrentDate();
    },
    comments() {
      this.updateCurrentDate();
    },
    users() {
      this.updateCurrentDate();
    }
  },
  methods: {
    updateCurrentDate() {
      this.currentDate = new Date().toISOString();
    }
  }
}
</script>
