// vue-3/src/components/Comment.vue
<template>
  <div class="card">
    <div class="card-body">
      <div class="text-sm mb-1">{{ comment.email }}</div>
      {{ comment.body }}
    </div>
  </div>
</template>

<script>
export default {
  name: 'CommentCard',
  props: {
    comment: {
      type: Object,
      required: true
    }
  }
}
</script>

// react-19-rc/src/components/Comment.jsx
import PropTypes from "prop-types"

export default function Comment({ comment }) {
  return (
    <div className="card">
      <div className="card-body">
        <div className="text-sm mb-1">{comment.email}</div>
        {comment.body}
      </div>
    </div>
  )
}

Comment.propTypes = {
  comment: PropTypes.object,
}
