// vue-3/src/components/UserCard.vue
<template>
  <div class="card">
    <div class="card-header">{{ user.name }}</div>
    <div class="card-body">
      <div>{{ user.company.name }}</div>
      <div>{{ user.website }}</div>
      <div>{{ user.email }}</div>
    </div>
    <div class="card-footer">
      <router-link class="btn" :to="user.id.toString()"> View </router-link>
    </div>
  </div>
</template>

<script>
export default {
  name: 'UserCard',
  props: {
    user: {
      type: Object,
      required: true
    }
  }
}
</script>

// react-19-rc/src/components/UserCard.jsx
import PropTypes from "prop-types"
import { Link } from "react-router-dom"

export default function UserCard({ user }) {
  return (
    <div className="card">
      <div className="card-header">{user.name}</div>
      <div className="card-body">
        <div>{user.company.name}</div>
        <div>{user.website}</div>
        <div>{user.email}</div>
      </div>
      <div className="card-footer">
        <Link className="btn" to={user.id.toString()}>
          View
        </Link>
      </div>
    </div>
  )
}

UserCard.propTypes = {
  user: PropTypes.object,
}
