// react-19-rc/src/components/Comment.jsx
import PropTypes from "prop-types"

export default function Comment({ comment }) {
  return (
    <div className="card">
      <div className="card-body">
        <div className="text-sm mb-1">{comment.email}</div>
        {comment.body}
      </div>
    </div>
  )
}

Comment.propTypes = {
  comment: PropTypes.object,
}

// angular-18/src/app/comment/comment.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comment',
  standalone: true,
  template: `
    <div class="card">
      <div class="card-body">
        <div class="text-sm mb-1">{{ comment.email }}</div>
        {{ comment.body }}
      </div>
    </div>
  `,
})
export class CommentCardComponent {
  @Input() comment: any;
}
